### ISSUE TITLE
Partial match on Python3 doesn't work if Levenshtein module is present 

### ISSUE THREAD

**Issue by ojomio** [seatgeek/fuzzywuzzy#63]
```
Traceback (most recent call last):
  File "./test_fuzzywuzzy.py", line 199, in testWRatioUnicodeString
    score = fuzz.WRatio(s1, s2, force_ascii=False)
  File "/tmp/pyphrasy/fuzzywuzzy/fuzzywuzzy/fuzz.py", line 255, in WRatio
    partial = partial_ratio(p1, p2) * partial_scale
  File "/tmp/pyphrasy/fuzzywuzzy/fuzzywuzzy/fuzz.py", line 77, in partial_ratio
    blocks = m.get_matching_blocks()
  File "/tmp/pyphrasy/fuzzywuzzy/fuzzywuzzy/StringMatcher.py", line 57, in get_matching_blocks
    self._str1, self._str2)
TypeError: inverse expected a list of edit operations

```

**Comment by josegonzalez** [comment]
I think you made the PR to @ztane's repository, so closing since this is fixed :)
